development:
    public: true
    site_name: 'Photos'
    #site_logo: 'logo.png'
    #s3_access_key_id: ''
    #s3_secret_access_key: ''
    #s3_bucket: ''
production:
    public: true
    site_name: 'Photos'
test:
    public: true
    site_name: 'Photos'